### ISSUE TITLE
Does 64.64 need solc version ^0.5.7? 

### ISSUE THREAD

**Issue by iamwilhelm** [abdk-consulting/abdk-libraries-solidity#1]
I'm wondering if the language version for solidity can be relaxed to `^0.5.0`? I read through the release change logs from 0.5.0 to 0.5.7, and most of the releases seem like improvements on the YUL optimizer and the ABIencoderV2. 

Are these changes needed to use ABDKMath64x64? I ask, because the current version of truffle (5.0.24) only has solidity 0.5.0.

**Comment by iamwilhelm** [comment]
Ah, but also this is low priority. I just saw that in truffle's config, you can upgrade to any version of solidity. 

https://github.com/trufflesuite/truffle/releases/tag/v5.0.0-beta.0#specify-a-solcjs-version

**Comment by 3sGgpQ8H** [comment]
Solidity 0.5.7 is the version of compiler the code was tested against.
