### ISSUE TITLE
hardhat compiler cannot parse pragma

### ISSUE THREAD

**Issue by moodysalem** [abdk-consulting/abdk-libraries-solidity#11]
hardhat cannot parse this pragma
https://github.com/abdk-consulting/abdk-libraries-solidity/blob/16d7e1dd8628dfa2f88d5dadab731df7ada70bdd/ABDKMath64x64.sol#L6

Replace with this to fix in all files
```solidity
pragma solidity >=0.5.0 <0.8.0;
```

**Comment by sambacha** [comment]
This isn't an issue with this library, in fact the versioning in this library is what is [specified in the official solidity documentation referenced here](https://docs.soliditylang.org/en/develop/layout-of-source-files.html?highlight=pragma#version-pragma):

"It is possible to specify more complex rules for the compiler version, these follow the same syntax used by npm."


> || includes multiple sets of versions
> examples:
> ^2 <2.2 || > 2.3


In fact most tooling does not recognize this usage of `||` for versioning. In fact the only tool I know that actually recognizes this pragma off the top of my head is [POA's Solidity Flattener](https://github.com/poanetwork/solidity-flattener)

Hope this helps,

Sam

**Comment by chanhosuh** [comment]
I think this issue can be closed.  The latest hardhat (2.0.8) uses the fixed solidity parser and I'm able to compile and use this library.
