### ISSUE TITLE
Update for solidity 0.8

### ISSUE THREAD

**Issue by jeffywu** [abdk-consulting/abdk-libraries-solidity#13]
Are there any plans to update this for Solidity 0.8+?

**Comment by 3sGgpQ8H** [comment]
For previous major releases like 0.6.0 and 0.7.0 it was as simple as to update `pragma` and retest with the new compiler, however for 0.8.0 the situation is more complicated.  As Solidity 0.8.x does overflow checks under cover, the current code, that also does the checks itself, would be suboptimal, however wrapping the current code into `unchecked` would be it incompatible with the older releases.
Currently, realistic plan is to have a separate branch for Solidity 0.8.0 with most of the explicit checks removed, but this is a decent amount of work to be done.

**Comment by jeffywu** [comment]
Fair enough. I'm keen on upgrading to 0.8 for my code and this library is a part of it. If there is a timeline let me know or we can just wrap our ABDK library to use `unchecked` for the 0.8 upgrade.

**Comment by 3sGgpQ8H** [comment]
Version 3.0 published that requires Solidity 0.8.x.  For older compilers 2.x versions will be published going forward.
