### ISSUE TITLE
Expand the documentation to explain the inner mathematical logic

### ISSUE THREAD

**Issue by paulrberg** [abdk-consulting/abdk-libraries-solidity#14]
# Description
I love ABDKMath64x64, it's ultra-fast, but whenever I end up inspecting the inner workings of the library, I stop for a couple of hours to deconstruct the mathematical logic.

For instance, take [log_2](https://github.com/abdk-consulting/abdk-libraries-solidity/blob/16d7e1dd8628dfa2f88d5dadab731df7ada70bdd/ABDKMath64x64.sol#L361-L390). The first part of the function is fairly intuitive, it applies the [find first one](https://en.wikipedia.org/wiki/Find_first_set) algorithm to determine the integer part of the binary logarithm. However, the second part is complicated. I can intuit that the goal is to calculate the fractional part of the binary logarithm, but I can't immediately figure out why that piece of code does that.

More specifically:

1. What is `ux`?
2. What is `b`?
3. Why shift to the right by `255`?
4. Why shift to the right by `127 + b`?
5. Does this perform an [iterative approximation](https://en.wikipedia.org/wiki/Binary_logarithm) of a binary logarithm of a number between [1,2), as you explained in [part 5](https://medium.com/coinmonks/math-in-solidity-part-5-exponent-and-logarithm-9aef8515136e) of your Math in Solidity series? If yes, I think that it would be very helpful to mention this.

# Proposal

Either:

1. Expand on the [ABDKMath64x64.md](https://github.com/abdk-consulting/abdk-libraries-solidity/blob/16d7e1dd8628dfa2f88d5dadab731df7ada70bdd/ABDKMath64x64.md) document to add references to the mathematical logic underpinning the library functions.
2. Create a [Gitbook](https://www.gitbook.com/)-powered documentation website, add again add more mathematical explanations.

**Comment by 3sGgpQ8H** [comment]
I've described the idea here: https://medium.com/coinmonks/math-in-solidity-part-5-exponent-and-logarithm-9aef8515136e
Also,
