### ISSUE TITLE
exp_2 doesn't work when x is 63

### ISSUE THREAD

**Issue by paulrberg** [abdk-consulting/abdk-libraries-solidity#15]
## Current Behaviour

Passing `0x3f0000000000000000` as the `x` argument for the `exp_2` function yields the following result:

<img width="1418" alt="Capture d’écran 2021-04-05 à 22 14 35" src="https://user-images.githubusercontent.com/8782666/113615276-54468f00-965c-11eb-9c55-0ea77ae7f25d.png">

But the function [lets](https://github.com/abdk-consulting/abdk-libraries-solidity/blob/v3.0/ABDKMath64x64.sol#L510) the input get near `0x400000000000000000`, which is more than `0x3f0000000000000000`.

## Expected Behaviour

~~I expected the function to return `0x8000000000000000`, which does fit within the 64.64 bit fixed-point number representation.~~

## Potential Solution

Limit the input to `0x3f0000000000000000`, or another value that is the actual true upper bound.

## Environment

+ Using [v3](https://github.com/abdk-consulting/abdk-libraries-solidity/tree/v3.0) of this repo
+ Solidity v0.8.3

**Comment by paulrberg** [comment]
## Update

It just dawned on me that reverting is the expected behaviour. Max 64x64 is 0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, which is `2^63 - 1` (duh, these are signed numbers).

Yet, I keep the issue open because x should not be allowed to get bigger than `0x3f0000000000000000`.

**Comment by 3sGgpQ8H** [comment]
It is possible to figure out the exact upper limit for `x` beyond which the `exp_2` function will throw and use it in the `require` statement, however this limit will make the code harder to read and the limit could become incorrect after further optimizations.  Setting such precise limit would reduce gas cost only for `x` values in the narrow range between the true limit and `0x400000000000000000`.  Doesn't seem worth doing.
