### ISSUE TITLE
Release for Solidity 0.8 support

### ISSUE THREAD

**Issue by NeoXtreem** [abdk-consulting/abdk-libraries-solidity#16]
When will the latest version of the code that supports Solidity 0.8 be released?

**Comment by ItsNickBarry** [comment]
It is released: https://github.com/abdk-consulting/abdk-libraries-solidity/releases/tag/v3.0
Not sure why `2.5` is marked as latest.

**Comment by NeoXtreem** [comment]
OK, then you might wanna fix this as `npm i abdk-libraries-solidity` gets 2.5.

**Comment by 3sGgpQ8H** [comment]
Fixed
