### ISSUE TITLE
I want to implement 4.pow(0.5)

### ISSUE THREAD

**Issue by TraderGalax** [abdk-consulting/abdk-libraries-solidity#17]
Can you help me, I want to implement 4.pow(0.5)
This calculation
What should I do

**Comment by jamesvan2019** [comment]
// x^y
     function pow(bytes16 x,uint256 y) private pure returns(bytes16 result){
        return ABDKMathQuad.pow_2(ABDKMathQuad.fromUInt(y).mul(x.log_2()));
    }

**Comment by 3sGgpQ8H** [comment]
You better ask such questions on https://ethereum.stackexchange.com
