### ISSUE TITLE
Display the Import

### ISSUE THREAD

**Issue by JimLynchCodes** [abdk-consulting/abdk-libraries-solidity#20]
README should have the import statement. thanks

**Comment by ItsNickBarry** [comment]
That seems unnecessary, as all of the contracts are in the root directory of the package.

Example: https://github.com/Premian-Labs/premia-contracts/blob/aabd867b39c5efbb5cf668115bc4c99581ce6145/contracts/pool/PoolWrite.sol#L6

**Comment by JimLynchCodes** [comment]
@ItsNickBarry  No offense, but no one wants to go searching for your garbage spaghetti letter puke that you call "code".

Pls add import to the README 👍

**Comment by 3sGgpQ8H** [comment]
Different teams use different ways to manage dependencies.  It is up to them how to import particular libraries.
