### ISSUE TITLE
Incorrect hardcoded value of 0x8 in sqrtu function (should be 0x4)

### ISSUE THREAD

**Issue by nonergodic** [abdk-consulting/abdk-libraries-solidity#22]
The hardcoded value [here](https://github.com/abdk-consulting/abdk-libraries-solidity/blob/d8817cb600381319992d7caa038bf4faceb1097f/ABDKMath64x64.sol#L739) is wrong.

0x8 = 1<<3 but it should be 1<<2 i.e. 0x4

I'm not sure how smart solc is (whether it will unroll loops if one cranks the optimization runs sufficiently high - I haven't tried it yet), but all of this could be avoided by

    using the 1 << shift syntax
    writing the entire thing as a loop (same with the 7x code repetition below)

**Comment by cleanunicorn** [comment]
@nonergodic Can you provide an input and an expected output for which the hardcoded value would create problems?
