### ISSUE TITLE
Some codes need optimization

### ISSUE THREAD

**Issue by gzliudan** [abdk-consulting/abdk-libraries-solidity#23]
I found this library from a third contract. And maybe some codes can be optimized to save gas. For example: `xc > 0x1` is better than `xc >= 0x2`. In Solidity, there is no single op-code for ≤ or ≥ expressions. Solidity compiler executes the LT/GT (less than/greater than) op-code and afterwards it executes an ISZERO op-code to check if the result of the previous comparison (LT/ GT) is zero and validate it or not. So the use of < and > are cheaper than ≤ and ≥.

**Comment by 3sGgpQ8H** [comment]
This should probably be reported to the Solidity team, as compiler should know how to use the available opcodes in the most efficient way.
