### ISSUE TITLE
Convert quadrouple precision float to readable decimal string

### ISSUE THREAD

**Issue by SteveH647** [abdk-consulting/abdk-libraries-solidity#24]
Hello,

I have a smart contract project that uses tons and tons of quadrouple precision floats, but it's hard to debug the code without the ability to convert the floats to readable decimal strings.  I need nearly all of the 113 bits of precision after the decimal point and I use tons of exp, ln, and pow functions.  Can this toString feature be added?  It's certainly an interesting problem to solve.  It's also acceptable and probably easier to write code that converts 128x128 fixed point precision into a decimal string.

Thank you

**Comment by 3sGgpQ8H** [comment]
Hello.  You can use ABDK Toolkit <https://toolkit.abdk.consulting/math#convert-number> for manual conversion: 
￼
Also, It is not that hard to code a toString function for quad precision numbers in any high-level programming language, such as JavaScript, Python etc.

--
Best regards,
Mikhail Vladimirov

**Comment by SteveH647** [comment]
Thank you very much.  That's a great toolkit.  I will also look into a high level language to do bulk conversions.
