### ISSUE TITLE
function exp returns same value regardless of input in ABDKMath64x64

### ISSUE THREAD

**Issue by bgits** [abdk-consulting/abdk-libraries-solidity#3]
Regardless of the input `function exp` returns `int128: 18446744073709551616`

This was tested using remix javascript VM and on Goerli. Solidity 0.5.7

**Comment by 3sGgpQ8H** [comment]
What arguments did you try?  Due to rounding errors, `exp(x)` may return the same value for different arguments in case argument values are close enough.
In my experiments `exp(1)=18446744073709551616` but `exp(2)=18446744073709551617`, so different results for different arguments.

**Comment by bgits** [comment]
Perhaps I'm misunderstanding the function, my understanding is that is should return `e^x`, in which case `exp(1) = 2...`, `exp(2) = 7...`. 

If the intention is as above then the calculation is off, otherwise perhaps a clarification on the function docstring.

**Comment by 3sGgpQ8H** [comment]
Both, argument and result are 64.64 fixed point numbers, so `1` means `1*2^-64`, and `18446744073709551616` means `18446744073709551616*2^-64`.  This is true for almost all functions within `ABDKMath64x64` library.  Where different number format is used, it is stated in docstring.

**Comment by paulrberg** [comment]
Hey @bgits, you may find useful this number converter developed by @3sGgpQ8H:

https://toolkit.abdk.consulting/math#convert-number
