### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by glowkeeper** [abdk-consulting/abdk-libraries-solidity#4]
Posted something similar on Reddit, too...

How do I convert decimal 22.35853544 into a signed 64.64-bit fixed-point number so I can use your library and do the following sum (for example):

`100 * ( 162494360000 / 200000000000 ) / 22.35853544`

I reckon a few examples like this would be useful...

**Comment by 3sGgpQ8H** [comment]
In order to convert a number to 64.64-bit fixed point, just multiply the number by 2^64 and round.
To convert from 64.64-bit fixed point, just divide by 2^64.

I've just enabled WiKi for this project and will start collecting FAQ there.

**Comment by glowkeeper** [comment]
So I just do `22.35853544 * 2**64`? In other words, something like:

````
denom= 22.35853544 * 2**64
interim = 100 * ( 162494360000 / 200000000000 ) / (denom)
answer = interim / 2**64
````


Similarly, if I had 2.03, the same `2.03 * 2**64` works? 

How does the library

**Comment by 3sGgpQ8H** [comment]
You basically need to convert all the inputs (100, 162494360000, 200000000000, 22.35853544) to 64.64-bit fixed point format, then use the library to perform calculations, then convert result back from 64.64-bit fixed point format.

**Comment by glowkeeper** [comment]
Ah, okay. 

So, in .js, something like:

```
const x= 22.35853544 * 2**64;
const y = 100 * 2**64;
const i = 162494360000 * 2**64;
const j = 200000000000 * 2**64;
```
Then, in .sol:

```
foo = ABDKMath64x64.div(i, j);
bar =  ABDKMath64x64.div(foo, x);
interim = ABDKMath64x64.mul(y, bar);
```
And back in .js:

```
const result = interim / 2**64;
```

Right?

**Comment by glowkeeper** [comment]
Just tried the above calcs, and I think `interim` overflows :( Unfortunately, gotta run out - be back later...

**Comment by 3sGgpQ8H** [comment]
Just tried myself using Google calculator and Remix:

    162494360000 * 2^64 ~ 2997491900000000000000000000000
    200000000000 * 2^64 ~ 3689348800000000000000000000000
    ABDKMath64x64.div (2997491900000000000000000000000,     3689348800000000000000000000000) = 14987459559886932870
    22.35853544 * 2^64 ~ 412442180000000000000
    ABDKMath64x64.div (14987459559886932870, 412442180000000000000) = 670323851979217653
    100 * 2^64 ~ 1844674400000000000000
    ABDKMath64x64.mul (1844674400000000000000, 670323851979217653) = 67032384930073572852
    67032384930073572852 / 2^64 ~ 3.6338328684

This seems to be correct answer: https://www.google.com/search?q=100+*+%28+162494360000+%2F+200000000000+%29+%2F+22.35853544&oq=100+*+%28+162494360000+%2F+200000000000+%29+%2F+22.35853544

**Comment by glowkeeper** [comment]
I had some issues passing `ABDKMath64x64` the correct stuff due to (_bignumber_) formatting issues via `Truffle`, but basically, it's doing what I need with something similar to this:

```
 int256 factor = int256(ABDKMath64x64.divi(old, new));
 int128 newFactor =  ABDKMath64x64.divi(factor, denom);
 return ABDKMath64x64.muli(newFactor, multiplier);
```

I'm a bit wary of that `int256` cast, but it seems to work (at the moment). Thanks for your help!

**Comment by 3sGgpQ8H** [comment]
While this may work in your particular case, in general this is improper use of `divi`.
As I've said before, `divi` basically converts simple fraction into 64.64-bit fixed point.  Simple fraction is `a/b`, where both, `a ` and `b` are integers.
In your case,  `factor = 162494360000 / 200000000000` is a simple fraction, but `newFactor = factor / 22.35853544` is obviously not, because neither numerator nor denominator are integers.

So, while using `divi` to calculate `factor` is fine, in order to calculate `newFactor` you should use `div` rather than `divi` and make sure, that both arguments are in 64.64-bit fixed point format.

**Comment by glowkeeper** [comment]
Apologies, my message glossed over some important detail. 

Outside of Solidity, I shift everything into the correct format by doing the necessary `* 2^64`. In other words, I have `162494360000 * 2^64`, `200000000000 * 2^64` and `22.35853544 * 2^64` etc. Hence, rather than `int128 newFactor =  ABDKMath64x64.divi(factor, 22.35853544)`, I'm doing `int128 newFactor =  ABDKMath64x64.divi(factor, 412442180000000000000)`. In which case, `ABDKMath64x64.divi` is correct, right?

**Comment by 3sGgpQ8H** [comment]
No.  Function `divi` accepts signed 256-bit integer numbers as numerator and denominator, not 64.64-bit fixed point numbers (thus `i` in the end).  If you've already converted your numbers to 64.64-bit fixed point format, then you should not pass them to `divi`.

**Comment by glowkeeper** [comment]
I see - but `divi` gives the right answer! 

Then _I think_ the problem I have is to do with number formats. 

Basically, I have to do "2.35853544 * 2^64" outside of Solidity (because of the fixed point), but _I think_ the resulting number does not fit into an int128, which is what `div` expects. It does, though, fit into either a uint128, or, more to the point, an int256, hence my use of `divi`.

**Comment by 3sGgpQ8H** [comment]
Surely 2.35853544 does fit, because 64.64-fixed point has 64 bits before the dot, so it can handle numbers up to 2^64, and 2.35853544 is definitely less than 2^64.

Main reason why `divi` is here is to make conversion of simple fractions into 64.64-bit fixed point safer.  Of cause, in order to convert simple fraction `a/b` one may convert `a`, then convert `b`, and then use `div` to divide them, but this will fail in case either `a` or `b` do not fit into 64.64-bit fixed point, even if `a/b` itself does fit.  Function `divi` solves this problem.

**Comment by glowkeeper** [comment]
> and 2.35853544 is definitely less than 2^64.

Yes, but `2.35853544 * 2^64` isn't, and when I pass that value into a Solidity function that takes an int128 as an argument, `solc` complains.

**Comment by 3sGgpQ8H** [comment]
Correct me if I'm wrong, but `2.35853544 * 2^64` is something between `2^65` and `2^66`, so way less than `2^127-1` which is the maximum value allowed for `int128` type in Solidity.

**Comment by glowkeeper** [comment]
> Correct me if I'm wrong, but 2.35853544 * 2^64 is something between 2^65 and 2^66, so way less than 2^127-1 which is the maximum value allowed for int128 type in Solidity.

That's right, isn't it - then I wonder why `solc` was complaining? I'll do some more digging around...

**Comment by glowkeeper** [comment]
I think my problems above were to do with some _wrinkle_ with `truffle` ;)

If I call solidity with this (via the _truffle migration script_):

```
web3.utils.toHex(22.35853544 * 2**64);
```
Then it all works properly, and I can do this:
```
int128 factor = ABDKMath64x64.div(old, new);
int128 newFactor =  ABDKMath64x64.div(factor, denom);
return ABDKMath64x64.mul(newFactor, multiplier);
```
In other words, it all works correctly - sorry for the confusion.

ps. I reckon this discussion could help others use this neat little library, so I reckon you should make it public, somehow. Maybe keep the issue _open_?

Thanks for your help!

**Comment by 3sGgpQ8H** [comment]
I will make FAQ page based on this discussion.
