### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by moodysalem** [abdk-consulting/abdk-libraries-solidity#6]
Want to use in @uniswap/lib package

Please add a license to this repo

**Comment by moodysalem** [comment]
I see a license in the README, if you could copy to the file `LICENSE` it would be helpful

**Comment by 3sGgpQ8H** [comment]
Will do

**Comment by 3sGgpQ8H** [comment]
Done.  The license is moved to a separate file.

**Comment by moodysalem** [comment]
It's usually just named LICENSE vs. LICENSE.md in GitHub repos (I'm not sure GitHub detects LICENSE.md)

**Comment by 3sGgpQ8H** [comment]
GitHub detected it.  Also, GitHub recommends this name: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#determining-the-location-of-your-license
