### ISSUE TITLE
Deploy to npm

### ISSUE THREAD

**Issue by moodysalem** [abdk-consulting/abdk-libraries-solidity#7]
We manage dependencies with npm, this would be extra useful deployed as an npm package

**Comment by 3sGgpQ8H** [comment]
It is already deployed https://www.npmjs.comr/package/abdk-libraries-solidity

**Comment by moodysalem** [comment]
Great! It’s helpful to add the package.json and information to the readme (eg an npm badge/link) so people know that package comes from this repo

**Comment by 3sGgpQ8H** [comment]
NPM is not a native package repository for Ethereum.  Source code cannot and shouldn't now about all the repositories where its artifacts are published.  The [releases](https://github.com/abdk-consulting/abdk-libraries-solidity/releases) page of this repository is the primary distribution location for the library, and NPM package is just repack convenient for those who use NPM as a dependency manager for Solidity libraries.

**Comment by moodysalem** [comment]
I think that's a very purist perspective. Given that most solidity development environments support npm and npm/yarn have all the necessary integrity features (package hashes, version locks) e.g. same as git subrepos, and many people use npm/yarn, it seems like it would be very useful information to surface either via `package.json` or the README.

Also, it is scary to use an npm package and not know that it is sourced from the author of this repo, since I have to check the package matches the repo myself. If there is a package.json I know that this package is associated with the npm package.

**Comment by stoplion** [comment]
I second that. Since it's already on NPM, why not add a package.json.
