### ISSUE TITLE
Open to license changes?

### ISSUE THREAD

**Issue by asselstine** [abdk-consulting/abdk-libraries-solidity#9]
The license for this code is the [BSD 4-clause license](https://en.wikipedia.org/wiki/BSD_licenses#4-clause_license_(original_%22BSD_License%22)), which includes a clause on advertising.

This license isn't compatible with the GPL.  Are you open to changing it to the BSD 3-clause license?

I'd love to use this excellent code but the licensing is not compatible with our codebase.  Thoughts?

**Comment by 3sGgpQ8H** [comment]
If you are just referring the library in your codebase, then there shouldn't be any unresolvable issues with licenses incompatibility.  See this answer: https://www.gnu.org/licenses/gpl-faq.en.html#GPLIncompatibleLibs for details.

**Comment by asselstine** [comment]
Right; it's possible to modify the GPL license, but ideally they can just be compatible out-of-the-box.

The other problem is that the clause itself is burdensome; having to include the sentence on all advertising materials is a pain.  Simply including the license in the codebase is much easier.  Would you be open to removing the clause?

**Comment by 3sGgpQ8H** [comment]
I would not call it “to modify GPL”.  I would call it “to use flexibility, deliberately put into GPL by its authors specifically for cases like this one”.  In my understanding, the incompatibility between GPL and 4-clause BSD license is that code licensed under 4-clause BSD license cannot be relicensed under GPL by a third party, and thus cannot be made a part of wider code base licensed under GPL.  This does not prevent code licensed under GPL to refer to a library licensed under 4-clause BSD license, and even to proprietary libraries.

Even if ABDK Libraries for Solidity would be licensed under 3-clause BSD or MIT license, there still would be a problems relicensing them under GPL, as GPL, as GPL requires source code to be public, and defines source code as preferred form to make changes, which in our case probably assumes, that tests and build scripts should also be published.

To be clear.  ABDK Libraries is not a free software as GPL understands it.  It is not a community work.  It is a product developed in-house by a commercial firm.  There are two main purposes, why we released it for free with source code open:

1. To show people better ways to do Math in Ethereum, as we believe that math done right is essential for Ethereum success, and Ethereum success is essential for success of our Ethereum-related business.  We were using these ways in our work for a long time, but the most of our work is private, thus most people were not aware of it.
2. To show people what level of quality they would get by ordering smart contract development from us.
